[db]
host = 127.0.0.1
port = 3306
user = gofly
password = gofly
database = gofly_single

[es]
host = http://127.0.0.1:9200
username = elastic
password = t1xB1UMy56lsZFE9E+Cv

[meeting]
offline_wav_path = /home/leozy/Desktop/developer/git/python/evoice/data/meeting/offline

[voice]
print_wav_path = /home/leozy/Desktop/developer/git/python/evoice/data/print
temp_path = /home/leozy/Desktop/developer/git/python/evoice/data/temp

[model]
cache_dir = /home/leozy/.cache/model
# 用于测试的模型
speech_test = /home/leozy/.cache/model/speech_test
# 训练完成的模型
speech_train = /home/leozy/.cache/model/speech_train

