[db]
host = 127.0.0.1
port = 3306
user = gofly
password = gofly
database = gofly_single

[es]
host = http://127.0.0.1:9200
username = elastic
password = vQ3+XUal8mHOt7onuaui

[meeting]
offline_wav_path = /home/zrway/evoice/audio/meeting/offline

[voice]
print_wav_path = /home/zrway/evoice/audio/voice/print
temp_path = /home/zrway/evoice/audio/voice/temp

[model]
cache_dir = /home/zrway/.cache/model
# 用于测试的模型
speech_test = /home/zrway/.cache/model/speech_test
# 训练完成的模型
speech_train = /home/zrway/.cache/model/speech_train


[llm]
# 阿里云百炼 DashScope API 配置
api_url = https://dashscope.aliyuncs.com/compatible-mode/v1
api_key = sk-509cc0f8f72b4f888d69854cbe250fb3
model = qwen-flash